<a href="https://colab.research.google.com/github/mottaquikarim/PYTH2/blob/master/src/PSETS/nb/homework_pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  PANDAS1 BASICS

## NDARRS

### P1.PY




In [0]:
"""
ndarray properties
"""

import numpy as np

# Creating array object
arr = np.array([[1, 2, 3],
                [4, 2, 5]])

# Given the above:

# Printing type of arr object
print("Array is of type: ", type(arr))  # how would you print type?

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)  # how would you print dimensions?

# Printing shape of array
print("Shape of array: ", arr.shape)  # how would you print "shape"

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)  # how would you print size?

# Printing type of elements in array
# how would you print element type?
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64




### P2.PY




In [0]:
"""
ndarrays operations 
"""

import numpy as np

# Create array from list with type float
a = np.array([1., 2., 3.])
print(a, a.dtype)

# Create array from tuple
b = np.array((1., 2., 3.))
print(b, b.dtype)


# Create a 3X4 array with all zeros
c = np.zeros([3, 4])
c = np.zeros([3, 4])
print(c)


[1. 2. 3.] float64
[1. 2. 3.] float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]




### P3.PY




In [0]:
"""
ndarray indexing
"""

import numpy as np

# given this
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# grab first two rows of arr
a = arr[0:2 , :]
print(a, )
print("------------")
# grab second and third row of arr
b = arr[2: , :]
print(b)
print("------------")
# grab first two rows of arr and first two columns
#ndArray[start_row_index : end_row_index , start_column_index : end_column_index]
columns = arr[0: 2 , 0: 4]
print(columns)
#No sure if we need only the 4 values from this matrix or the whole row and the whole column 
print("------------")

#grab elements at indices (0, 3) = 0, (1, 2) = 6, (2, 1) = 0, (3, 0) = 3
d0 = arr[0][2]
d1 = arr[1][2]
d2 = arr[2][1]
d3 = arr[3][0]

print(d0, d1, d2, d3)


# grab elements > 0
e = None


[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]]
------------
[[ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
------------
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]]
------------
0.0 6.0 0.0 3.0




### P4.PY




In [0]:
"""
basic operations
"""

import numpy as np

a1 = np.array([1, 2, 5, 3])

# add 1 to every element
a = a1 + 1
print("Adding 1 to every element:", a)

# subtract 3 from each element
b = a1 - 3
print("Subtracting 3 from each element:", b)

# multiply each element by 10
c = a1 * 10
print("Multiplying each element by 10:", c)

# square each element
d = a1 ** a1
print("Squaring each element:", d)

# Doubled each element of original array
print("Doubled each element of original array:", )
# not sure what this means?

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [   1    4 3125   27]
Doubled each element of original array:




### P5.PY




In [0]:
"""
basic operations II
"""

import numpy as np

arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

# maximum element of array
print("Largest element is:", np.amax(arr))

# minimum element of array
print("Smallest element is:", np.amin(arr))

# maximum element per row
print("Row-wise maximum elements:", [np.amax(arr[0]), np.amax(arr[1]), np.amax(arr[2])])

# minimum element per col
print("Column-wise minimum elements:",
      [np.amin(arr[0]), np.amin(arr[1]), np.amin(arr[2])])

# sum of array elements
print("Sum of all array elements:", np.sum(arr))

# cumulative sum along each row
print("Cumulative sum along each row:\n", np.sum(arr[0]), np.sum(arr[1]), np.sum(arr[2]))

print("------------")

c = np.array([[1, 2],
              [3, 4]])
d = np.array([[4, 3],
              [2, 1]])

# add arrays
c1 = np.sum(c)
d1 = np.sum(d)
print("Array sum:\n", (c1 + d1))

print("------------")

# multiply arrays (elementwise multiplication)
c2 = (c*d)
#Not sure how to get the table from here 
print("Array multiplication:\n", None)


Largest element is: 9
Smallest element is: 1
Row-wise maximum elements: [6, 7, 9]
Column-wise minimum elements: [1, 2, 1]
Sum of all array elements: 38
Cumulative sum along each row:
 12 13 13
------------
Array sum:
 20
------------
[[4 6]
 [6 4]]
Array multiplication:
 None




## SERIES

### P1.PY




In [0]:
"""
Simple Series
"""


# import pandas as pd
import pandas as pd

# import numpy as np
import numpy as np


# simple array
data = np.array(['l', 'a', 'y', 'l', 'a'])

# convert data to series
ser = pd.Series(index=['l', 'a', 'y', 'l', 'a'])
print(ser)

# grab the first three items from ser
sub = ser.head(3)
print(sub)

# create series with custom label such that:
"""
a    l
b    a
c    y
d    l
e    a
dtype: object
"""
ser2 = pd.Series(index=[['a','b','c','d','e'],['l', 'a', 'y', 'l', 'a']])
print(ser2)

# access "y" from series ser2
print("accessing 'y'", ser2['c'])




l   NaN
a   NaN
y   NaN
l   NaN
a   NaN
dtype: float64
l   NaN
a   NaN
y   NaN
dtype: float64
a  l   NaN
b  a   NaN
c  y   NaN
d  l   NaN
e  a   NaN
dtype: float64
accessing 'y' y   NaN
dtype: float64




### P2.PY




In [11]:
"""
Indexing and Selecting Series
"""

# import pandas as pd
import pandas as pd

# import numpy as np
import numpy as np

# create a new series
s = pd.Series(np.nan, index=[49, 48, 47, 46, 45, 1, 2, 3, 4, 5])
print(s)

# using iloc, get the first 3 items in series
t = s.iloc(2)
print(t)

# using loc, do the same
u = None

# using index operators, do the same
v = None


49   NaN
48   NaN
47   NaN
46   NaN
45   NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
dtype: float64


ValueError: ignored



### P3.PY




In [0]:
"""
Series operations
"""

# importing pandas module
import pandas as pd

# creating a series
data1 = pd.Series([5, 2, 3, 7], index=['a', 'b', 'c', 'd'])
print(data1)

# creating a series
data2 = pd.Series([1, 6, 4, 9], index=['a', 'b', 'd', 'e'])
print(data2)

# add data1 and data2
data3 = data1 + data2
print(data3)

# subtract data1 and data2
data4 = data1 - data3
print(data4)


a    5
b    2
c    3
d    7
dtype: int64
a    1
b    6
d    4
e    9
dtype: int64
a     6.0
b     8.0
c     NaN
d    11.0
e     NaN
dtype: float64
a   -1.0
b   -6.0
c    NaN
d   -4.0
e    NaN
dtype: float64




#  PANDAS1 WINE REVIEWS

## CHECK_IMPORTED_DATA

### P1.PY




In [0]:
"""
Checking Imported Data I - Data Dictionary
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')


# Access a summary of the core metadata of the DataFrame (i.e. the number and name of columns, the rows, etc.)

wine_reviews.describe()

cols = wine_reviews.columns
for idx, col in enumerate(cols):
  print(idx+1, col)


1 Unnamed: 0
2 country
3 description
4 designation
5 points
6 price
7 province
8 region_1
9 region_2
10 taster_name
11 taster_twitter_handle
12 title
13 variety
14 winery




### P2.PY




In [0]:
"""
Checking Imported Data II - How Big is the Data?
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')


# Print the number of rows and columns in wine_reviews.
wine_reviews.shape

# Print the number of elements in wine_reviews.
wine_reviews.size


1819594



### P3.PY




In [0]:
"""
Checking Imported Data III - DataFrame Labels
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')


# Access the labels on the rows of data.

wine_reviews.columns


# Access the labels on the columns of data.

wine_reviews.head()

# Return the labels for the rows and columns in wine_reviews in one command.

wine_reviews[columns]


Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')



### P4.PY




In [0]:
"""
Checking Imported Data IV - Preview Data
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')


# Print out the first and last 10 rows of data.

wine_reviews.head(10)
wine_reviews.tail(10)




## SELECTING_DATA

### P1.PY




In [0]:
"""
Selecting Data I - Access a Row
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')


# Return the 12th row in the wine_reviews dataframe.
wine_reviews.iloc[12]



Unnamed: 0                                                              12
country                                                                 US
description              Slightly reduced, this wine offers a chalky, t...
designation                                                            NaN
points                                                                  87
price                                                                   34
province                                                        California
region_1                                                  Alexander Valley
region_2                                                            Sonoma
taster_name                                                 Virginie Boone
taster_twitter_handle                                              @vboone
title                    Louis M. Martini 2012 Cabernet Sauvignon (Alex...
variety                                                 Cabernet Sauvignon
winery                   



### P2.PY




In [16]:
"""
Selecting Data II - Access a Column
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')

# Return the winery column in a variable called "wineries".

wineries = wine_reviews["winery"]

# Run a command to return the type of wineries.
type(wineries.dtypes)


numpy.dtype



### P3.PY




In [0]:
"""
Selecting Data III - Access Single Values
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')

# Print the value in the 5th column of the 7th row.
wine_reviews.loc[5, "region_1"]

# Create a Series called "countries" from the 'country' column and print item at index 18.



# Print the 10th item in countries.


'Navarra'



### P4.PY




In [0]:
"""
Selecting Data IV - Access Slices
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('../winemag-data-130k.csv')


# Print first 3 values in the 'province' column.



# Create a Series called "provinces" and print the first 3 values.





### P5.PY




In [15]:
"""
Selecting Data V - Subsets
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')

# Create a new dataframe called "wine_ratings" that is a subset of wine_reviews. 
# It should have these columns in this order:
### title
### country
### points
### price

wine_ratings = wine_reviews[['title', 'country', 'points', 'price']]

wine_ratings.head(5)

title   country  points  price
0                  Nicosia 2013 Vulkà Bianco  (Etna)     Italy      87    NaN
1      Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portugal      87   15.0
2      Rainstorm 2013 Pinot Gris (Willamette Valley)        US      87   14.0
3  St. Julian 2013 Reserve Late Harvest Riesling ...        US      87   13.0
4  Sweet Cheeks 2012 Vintner's Reserve Wild Child...        US      87   65.0



### P6.PY




In [0]:
"""
Selecting Data VI - Min & Max (CHALLENGE!)
"""

import numpy as np
import pandas as pd
wine_reviews = pd.read_csv('winemag-data-130k.csv')


# Find the 5 rows with the highest-priced wine and the 5 rows with the lowest-priced wine. Assign them to variables called 'a' and 'b' respectively. Print 'a' and 'b'.



# Create a function to print out the variety and price of some number of the most and least expensive wines. Hints:
### It should contain loops
### The number function should take any number for finding the highest and lowest priced wines (e.g. top and bottom 5, top and bottom 10, etc.)
### If you're iterating through a 2 column dataframe item by item, remember the counting goes like this:
"""
[0,0], [0,1]
[1,0], [1,1]
[2,0], [2,1]
[3,0], [3,1]
[4,0], [4,1]
"""

